// <auto-generated />
using System;
using GamesAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesAPI.Migrations
{
    [DbContext(typeof(DbMainContext))]
    partial class DbMainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GamesAPI.Models.DeveloperStudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeveloperStudio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("32d88b31-afa7-42ef-9e63-352c398408ba"),
                            Name = "ActivisionBlizzard"
                        },
                        new
                        {
                            Id = new Guid("940467c3-32d2-4149-bd8b-d1876bae1318"),
                            Name = "Valve"
                        },
                        new
                        {
                            Id = new Guid("cfac1b0d-5780-4f6e-bf8e-53d1ed19536d"),
                            Name = "Panic Button Games"
                        });
                });

            modelBuilder.Entity("GamesAPI.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ddabede-af78-414e-a786-9368f74a7abb"),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("67c016fa-99cc-43af-b626-3809f38971b6"),
                            Name = "MMO RPG"
                        },
                        new
                        {
                            Id = new Guid("9b75d1cb-b714-41ed-b0df-be8ffdb10e26"),
                            Name = "Shooter"
                        });
                });

            modelBuilder.Entity("GamesAPI.Models.VideoGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeveloperStudioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperStudioId");

                    b.ToTable("VideoGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb1f1b39-12ea-4458-9d36-51dac268fe21"),
                            DeveloperStudioId = new Guid("32d88b31-afa7-42ef-9e63-352c398408ba"),
                            Name = "World of warcraft"
                        },
                        new
                        {
                            Id = new Guid("b6adad18-ffd2-4cf2-add4-b03c462c5b62"),
                            DeveloperStudioId = new Guid("940467c3-32d2-4149-bd8b-d1876bae1318"),
                            Name = "Left 4 Dead"
                        },
                        new
                        {
                            Id = new Guid("eee8f6ea-2096-47fb-a4a1-9de9cd41771d"),
                            DeveloperStudioId = new Guid("940467c3-32d2-4149-bd8b-d1876bae1318"),
                            Name = "Half-Life 2"
                        },
                        new
                        {
                            Id = new Guid("d03ef913-6d54-41cc-8f59-4a5a90b4d292"),
                            DeveloperStudioId = new Guid("cfac1b0d-5780-4f6e-bf8e-53d1ed19536d"),
                            Name = "Apex Legends"
                        });
                });

            modelBuilder.Entity("GamesAPI.Models.VideoGameGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GenreId");

                    b.ToTable("VideoGameGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4387219-6daa-4e9b-ae04-5037cd911332"),
                            GameId = new Guid("cb1f1b39-12ea-4458-9d36-51dac268fe21"),
                            GenreId = new Guid("67c016fa-99cc-43af-b626-3809f38971b6")
                        },
                        new
                        {
                            Id = new Guid("782412f4-53cb-402e-a830-21a5b43be849"),
                            GameId = new Guid("b6adad18-ffd2-4cf2-add4-b03c462c5b62"),
                            GenreId = new Guid("9b75d1cb-b714-41ed-b0df-be8ffdb10e26")
                        },
                        new
                        {
                            Id = new Guid("4d95eb9b-4fb4-4a35-96af-d71961fff409"),
                            GameId = new Guid("b6adad18-ffd2-4cf2-add4-b03c462c5b62"),
                            GenreId = new Guid("8ddabede-af78-414e-a786-9368f74a7abb")
                        },
                        new
                        {
                            Id = new Guid("7b878b48-17fc-4142-b466-153005e439bf"),
                            GameId = new Guid("eee8f6ea-2096-47fb-a4a1-9de9cd41771d"),
                            GenreId = new Guid("9b75d1cb-b714-41ed-b0df-be8ffdb10e26")
                        },
                        new
                        {
                            Id = new Guid("3bfbd03d-bf3a-4137-863e-b89ff446d87c"),
                            GameId = new Guid("eee8f6ea-2096-47fb-a4a1-9de9cd41771d"),
                            GenreId = new Guid("8ddabede-af78-414e-a786-9368f74a7abb")
                        },
                        new
                        {
                            Id = new Guid("2b5c4fb6-d563-4f31-aeac-60e8c16102ee"),
                            GameId = new Guid("d03ef913-6d54-41cc-8f59-4a5a90b4d292"),
                            GenreId = new Guid("9b75d1cb-b714-41ed-b0df-be8ffdb10e26")
                        });
                });

            modelBuilder.Entity("GamesAPI.Models.VideoGame", b =>
                {
                    b.HasOne("GamesAPI.Models.DeveloperStudio", "DeveloperStudio")
                        .WithMany()
                        .HasForeignKey("DeveloperStudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeveloperStudio");
                });

            modelBuilder.Entity("GamesAPI.Models.VideoGameGenre", b =>
                {
                    b.HasOne("GamesAPI.Models.VideoGame", "Game")
                        .WithMany("Genres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesAPI.Models.Genre", "Genre")
                        .WithMany("Genres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GamesAPI.Models.Genre", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("GamesAPI.Models.VideoGame", b =>
                {
                    b.Navigation("Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
